/* Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Architecture defines (unchanged, system-dependent) */
#define ARCH_X86 1
#define ARCH_X86_64 1

/* Version-specific defines */
#ifdef GEGL_05
  #define GEGL_LIBRARY "gegl-0.5"
  #define GEGL_MAJOR_VERSION 0
  #define GEGL_MINOR_VERSION 5
  #define GEGL_MICRO_VERSION 0  /* Initial 0.5 release; adjust as needed */
  #define GETTEXT_PACKAGE "gegl-0.5"
#else
  #define GEGL_LIBRARY "gegl-0.4"
  #define GEGL_MAJOR_VERSION 0
  #define GEGL_MINOR_VERSION 4
  #define GEGL_MICRO_VERSION 34
  #define GETTEXT_PACKAGE "gegl-0.4"
#endif

/* Stability flag (stable for both 0.4 and 0.5 releases) */
#undef GEGL_UNSTABLE

/* System-detected feature defines (unchanged from your original) */
#define HAVE_EXECINFO_H
#define HAVE_FSYNC
#undef HAVE_GEXIV2
#undef HAVE_LUA
#define HAVE_MALLOC_TRIM
#undef HAVE_MRG
#define HAVE_STRPTIME
#define HAVE_UNISTD_H
